db-url: ${DB_URL:jdbc:postgresql://localhost:5432/tasks}
db-username: ${DB_USERNAME:postgres}
db-password: ${DB_PASSWORD:postgres}
debug-mode: ${DEBUG_MODE:false}

jwt:
  token:
    secret: 4E645267556A586E3272357538782F413F4428472B4B6250655368566D597133
    expired: 3600000


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db-url}
    username: ${db-username}
    password:  ${db-password}

  liquibase:
    enabled: true
    driver-class-name: org.postgresql.Driver
    url: ${db-url}
    user: ${db-username}
    password: ${db-password}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
